# pandas

In [1]:
#pip install pandas

In [2]:
import pandas as pd
import numpy as np

# Series

In [3]:
pd.Series(dtype='float64')#Empty Series

Series([], dtype: float64)

In [4]:
la=['a','b','c']
m=[10,20,30]
a=np.array([10,20,30])
d={'a':10,'b':20,'c':30}

In [5]:
pd.Series(m)

0    10
1    20
2    30
dtype: int64

# Series with list and labels

In [6]:
pd.Series(data=m,index=la)

a    10
b    20
c    30
dtype: int64

# Using Dictionary

In [7]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

## series from numpy array

In [8]:
pd.Series(a)

0    10
1    20
2    30
dtype: int32

In [9]:
pd.Series(a,la)

a    10
b    20
c    30
dtype: int32

## Data in a series

In [10]:
#Using an Index
ser1=pd.Series([1,2,3,4],index=['ptk','kullu','Shimla','Mohali'])
ser1

ptk       1
kullu     2
Shimla    3
Mohali    4
dtype: int64

In [11]:
ser2=pd.Series([1,3,5,4],index=['ptk','kullu','Una','Mohali'])
ser2

ptk       1
kullu     3
Una       5
Mohali    4
dtype: int64

In [12]:
ser1['ptk']

1

In [13]:
ser2['Una']

5

## Operation

In [14]:
ser1-ser2

Mohali    0.0
Shimla    NaN
Una       NaN
kullu    -1.0
ptk       0.0
dtype: float64

In [15]:
ser1+ser2

Mohali    8.0
Shimla    NaN
Una       NaN
kullu     5.0
ptk       2.0
dtype: float64

In [16]:
ser1*ser2

Mohali    16.0
Shimla     NaN
Una        NaN
kullu      6.0
ptk        1.0
dtype: float64

In [17]:
ser1/ser2

Mohali    1.000000
Shimla         NaN
Una            NaN
kullu     0.666667
ptk       1.000000
dtype: float64

In [18]:
np.sin(ser1)

ptk       0.841471
kullu     0.909297
Shimla    0.141120
Mohali   -0.756802
dtype: float64

In [19]:
np.log(ser2)

ptk       0.000000
kullu     1.098612
Una       1.609438
Mohali    1.386294
dtype: float64

Usage of copy =False or True

In [20]:
r=[7,8]
ser=pd.Series(r,copy=True)
ser.iloc[0]=20
r

[7, 8]

In [21]:
ser

0    20
1     8
dtype: int64

In [22]:
#if copy=false
r1=[7,8]
ser1=pd.Series(r1,copy=False)
ser1.iloc[0]=20
r1

[7, 8]

In [23]:
ser1

0    20
1     8
dtype: int64

# Dataframe



syntax-pandas.DataFrame(data,index,columns,dtype,copy)


In [24]:
pd.DataFrame()

Empty DataFrame
Columns: []
Index: []

In [25]:
a=pd.DataFrame(np.random.randn(5,4),index='A B C D E'.split(),columns='W X Y Z'.split())
a

W         X         Y         Z
A -1.327284  1.545148  0.197933  0.572239
B -0.388238 -0.934072  0.479538  0.550341
C -0.213882  0.635796  0.519262 -0.355437
D  0.143455 -0.815083 -0.036376 -0.750863
E -0.586329 -0.531898 -0.605650  0.669804

In [26]:
d={
    "Name": ['Rohit','Aryan','Ayush','Yash','Neha','Suraj'],
    "Subject": ['Python','PHP','Java','C++','Ruby','Javascript'],
    "Marks": [70,77,75,67,85,90],
    "Highest Marks":[43,30,25,40,32,45]
}

In [27]:
df=pd.DataFrame(d)
df

Name     Subject  Marks  Highest Marks
0  Rohit      Python     70             43
1  Aryan         PHP     77             30
2  Ayush        Java     75             25
3   Yash         C++     67             40
4   Neha        Ruby     85             32
5  Suraj  Javascript     90             45

In [28]:
#inspecting data in DataFrame
df.head(2)

Name Subject  Marks  Highest Marks
0  Rohit  Python     70             43
1  Aryan     PHP     77             30

In [29]:
#GEt last value from the dataframe
df.tail(1)

Name     Subject  Marks  Highest Marks
5  Suraj  Javascript     90             45

In [30]:
df.sample(2)

Name     Subject  Marks  Highest Marks
5  Suraj  Javascript     90             45
0  Rohit      Python     70             43

In [31]:
df.dtypes

Name             object
Subject          object
Marks             int64
Highest Marks     int64
dtype: object

In [32]:
#get the index value
df.index

RangeIndex(start=0, stop=6, step=1)

In [33]:
df.columns

Index(['Name', 'Subject', 'Marks', 'Highest Marks'], dtype='object')

# Statistical summary of records

In [34]:
df.describe()

Marks  Highest Marks
count   6.000000       6.000000
mean   77.333333      35.833333
std     8.778762       7.985403
min    67.000000      25.000000
25%    71.250000      30.500000
50%    76.000000      36.000000
75%    83.000000      42.250000
max    90.000000      45.000000

In [35]:
df['Marks'].describe()

count     6.000000
mean     77.333333
std       8.778762
min      67.000000
25%      71.250000
50%      76.000000
75%      83.000000
max      90.000000
Name: Marks, dtype: float64

In [36]:
df.describe(include='all')

Name Subject      Marks  Highest Marks
count       6       6   6.000000       6.000000
unique      6       6        NaN            NaN
top     Rohit  Python        NaN            NaN
freq        1       1        NaN            NaN
mean      NaN     NaN  77.333333      35.833333
std       NaN     NaN   8.778762       7.985403
min       NaN     NaN  67.000000      25.000000
25%       NaN     NaN  71.250000      30.500000
50%       NaN     NaN  76.000000      36.000000
75%       NaN     NaN  83.000000      42.250000
max       NaN     NaN  90.000000      45.000000

In [37]:
df.describe(include=np.number)

Marks  Highest Marks
count   6.000000       6.000000
mean   77.333333      35.833333
std     8.778762       7.985403
min    67.000000      25.000000
25%    71.250000      30.500000
50%    76.000000      36.000000
75%    83.000000      42.250000
max    90.000000      45.000000

In [38]:
df.describe(include=[object])

Name Subject
count       6       6
unique      6       6
top     Rohit  Python
freq        1       1

In [39]:
d=pd.DataFrame({'categorical':pd.Categorical(['d','e','f']),
               'numeric':[1,2,3],
               'object':['a','b','c']
               })
d.describe(include=['category'])


categorical
count            3
unique           3
top              d
freq             1

In [40]:
#skip numeric columns from a Dataframe
df.describe(exclude=[object])

Marks  Highest Marks
count   6.000000       6.000000
mean   77.333333      35.833333
std     8.778762       7.985403
min    67.000000      25.000000
25%    71.250000      30.500000
50%    76.000000      36.000000
75%    83.000000      42.250000
max    90.000000      45.000000

In [41]:
df.describe(exclude=[np.number])

Name Subject
count       6       6
unique      6       6
top     Rohit  Python
freq        1       1

# Sorting records

In [42]:
df.sort_values('Marks',ascending=False)

Name     Subject  Marks  Highest Marks
5  Suraj  Javascript     90             45
4   Neha        Ruby     85             32
1  Aryan         PHP     77             30
2  Ayush        Java     75             25
0  Rohit      Python     70             43
3   Yash         C++     67             40

# Slicing Records

In [43]:
df['Subject']

0        Python
1           PHP
2          Java
3           C++
4          Ruby
5    Javascript
Name: Subject, dtype: object

In [44]:
df.Subject

0        Python
1           PHP
2          Java
3           C++
4          Ruby
5    Javascript
Name: Subject, dtype: object

In [45]:
df[['Name','Subject']]

Name     Subject
0  Rohit      Python
1  Aryan         PHP
2  Ayush        Java
3   Yash         C++
4   Neha        Ruby
5  Suraj  Javascript

In [46]:
df[['Name','Subject','Marks']]

Name     Subject  Marks
0  Rohit      Python     70
1  Aryan         PHP     77
2  Ayush        Java     75
3   Yash         C++     67
4   Neha        Ruby     85
5  Suraj  Javascript     90

In [47]:
df[['Name','Subject','Highest Marks']]

Name     Subject  Highest Marks
0  Rohit      Python             43
1  Aryan         PHP             30
2  Ayush        Java             25
3   Yash         C++             40
4   Neha        Ruby             32
5  Suraj  Javascript             45

In [48]:
df[['Name','Highest Marks']]

Name  Highest Marks
0  Rohit             43
1  Aryan             30
2  Ayush             25
3   Yash             40
4   Neha             32
5  Suraj             45

# Dataframe Columns are just series

In [49]:
#check type of columnes of DataFrame 
type[df['Subject']]

type[0        Python
1           PHP
2          Java
3           C++
4          Ruby
5    Javascript
Name: Subject, dtype: object]

In [50]:
type(df)

pandas.core.frame.DataFrame

In [51]:
df[0:3]

Name Subject  Marks  Highest Marks
0  Rohit  Python     70             43
1  Aryan     PHP     77             30
2  Ayush    Java     75             25

In [52]:
#find the data  by index 
df.iloc[2]

Name             Ayush
Subject           Java
Marks               75
Highest Marks       25
Name: 2, dtype: object

In [53]:
#loc we have to define name and location
df.loc[2,'Subject']

'Java'

In [54]:
df.iloc[2,1]

'Java'

Creating a new column

In [55]:
df['new_col']=df['Marks']+df['Highest Marks']

In [56]:
df

Name     Subject  Marks  Highest Marks  new_col
0  Rohit      Python     70             43      113
1  Aryan         PHP     77             30      107
2  Ayush        Java     75             25      100
3   Yash         C++     67             40      107
4   Neha        Ruby     85             32      117
5  Suraj  Javascript     90             45      135

Removing Columns

In [57]:
df.drop('new_col',axis=1)

Name     Subject  Marks  Highest Marks
0  Rohit      Python     70             43
1  Aryan         PHP     77             30
2  Ayush        Java     75             25
3   Yash         C++     67             40
4   Neha        Ruby     85             32
5  Suraj  Javascript     90             45

In [58]:
df.drop(4,axis=0)

Name     Subject  Marks  Highest Marks  new_col
0  Rohit      Python     70             43      113
1  Aryan         PHP     77             30      107
2  Ayush        Java     75             25      100
3   Yash         C++     67             40      107
5  Suraj  Javascript     90             45      135

In [59]:
df.drop('new_col',axis=1,inplace=True)

In [60]:
df

Name     Subject  Marks  Highest Marks
0  Rohit      Python     70             43
1  Aryan         PHP     77             30
2  Ayush        Java     75             25
3   Yash         C++     67             40
4   Neha        Ruby     85             32
5  Suraj  Javascript     90             45

# Condition Sdelection or filtering

In [61]:
df['Marks']>50

0    True
1    True
2    True
3    True
4    True
5    True
Name: Marks, dtype: bool

In [62]:
df[df['Marks']>70]

Name     Subject  Marks  Highest Marks
1  Aryan         PHP     77             30
2  Ayush        Java     75             25
4   Neha        Ruby     85             32
5  Suraj  Javascript     90             45

Another way to filter data is using isin

In [63]:
df[df['Name'].isin(['Suraj','Yash'])]

Name     Subject  Marks  Highest Marks
3   Yash         C++     67             40
5  Suraj  Javascript     90             45

In [64]:
#get name having more than 70
df[df['Marks']>70]['Name']

1    Aryan
2    Ayush
4     Neha
5    Suraj
Name: Name, dtype: object

In [65]:
#get names and subject having highest marks
df[df['Marks']>35][['Name','Subject']]

Name     Subject
0  Rohit      Python
1  Aryan         PHP
2  Ayush        Java
3   Yash         C++
4   Neha        Ruby
5  Suraj  Javascript

In [66]:
#get DataFrame having Marks more than 70 or highest marks more than 35
df[(df['Marks']>35) | (df['Highest Marks']>35)]

Name     Subject  Marks  Highest Marks
0  Rohit      Python     70             43
1  Aryan         PHP     77             30
2  Ayush        Java     75             25
3   Yash         C++     67             40
4   Neha        Ruby     85             32
5  Suraj  Javascript     90             45

In [67]:
#get dataframe having marks more than 70 and highest marks more than 30
df[(df['Marks']>35) & (df['Highest Marks']>30)]

Name     Subject  Marks  Highest Marks
0  Rohit      Python     70             43
3   Yash         C++     67             40
4   Neha        Ruby     85             32
5  Suraj  Javascript     90             45

# Rename column
Syntax-df.rename()

In [68]:
df.columns

Index(['Name', 'Subject', 'Marks', 'Highest Marks'], dtype='object')

In [69]:
df.rename(columns={'Highest Marks':'Avg Marks'},inplace=True)

In [70]:
df

Name     Subject  Marks  Avg Marks
0  Rohit      Python     70         43
1  Aryan         PHP     77         30
2  Ayush        Java     75         25
3   Yash         C++     67         40
4   Neha        Ruby     85         32
5  Suraj  Javascript     90         45

 1. Write a Pandas program to create a dataframe from a dictionary and display it.
Sample data: {'X':[78,85,96,80,86], 'Y':[84,94,89,83,86],'Z':[86,97,96,72,83]}



In [73]:
Sample_data = {'X':[78,85,96,80,86], 'Y':[84,94,89,83,86],'Z':[86,97,96,72,83]}
a=pd.DataFrame(Sample_data)
a

X   Y   Z
0  78  84  86
1  85  94  97
2  96  89  96
3  80  83  72
4  86  86  83

2. Write a Pandas program to select the 'name' and 'score' columns from the following DataFrame.
Sample Python dictionary data and list labels:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']


In [74]:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']


In [75]:
a=pd.DataFrame(exam_data)
a[['name','score']]

name  score
0  Anastasia   12.5
1       Dima    9.0
2  Katherine   16.5
3      James    NaN
4      Emily    9.0
5    Michael   20.0
6    Matthew   14.5
7      Laura    NaN
8      Kevin    8.0
9      Jonas   19.0

3. Select 'name' and 'score' columns in rows 1, 3, 5, 6 from the above data frame.

In [76]:
a.loc[[1, 3, 5, 6],['name','score']]

name  score
1     Dima    9.0
3    James    NaN
5  Michael   20.0
6  Matthew   14.5

4. Write a Pandas program to select the rows where the number of attempts in the examination is greater than 2.

In [77]:
a[a['attempts']>2]

name  score  attempts qualify
1     Dima    9.0         3      no
3    James    NaN         3      no
5  Michael   20.0         3     yes

In [78]:
(a.iloc[[1,3,5,6],[0,1]])

name  score
1     Dima    9.0
3    James    NaN
5  Michael   20.0
6  Matthew   14.5

5.  Write a Pandas program to select the rows the score is between 15 and 20 (inclusive).


In [79]:
a[(a['score']>15) &  (a['score']<20)]

name  score  attempts qualify
2  Katherine   16.5         2     yes
9      Jonas   19.0         1     yes

# Data Wrangling

In [80]:
d={
    'Student_id':['1','2','3','4','5'],
    'Student_name':['Kartik','Shruti','Aryan','Sehaj','Yamini'],
    'Marks':[60,55,70,80,75]
}
df1=pd.DataFrame(d, columns=['Student_id','Student_name','Marks'])

In [81]:
d1={
    'Student_id':['4','5','6','7','8'],
    'Student_name':['Shruti','Sehaj','Rajat','Puneet','Rajat'],
    'Marks':[70,65,60,85,95]
}
df2=pd.DataFrame(d1, columns=['Student_id','Student_name','Marks'])

In [82]:
df1

Student_id Student_name  Marks
0          1       Kartik     60
1          2       Shruti     55
2          3        Aryan     70
3          4        Sehaj     80
4          5       Yamini     75

In [83]:
pd.merge(df1,df2)

Empty DataFrame
Columns: [Student_id, Student_name, Marks]
Index: []

# Grouping

In [84]:
group=df2.groupby('Student_name')
g= group.get_group('Rajat')
g

Student_id Student_name  Marks
2          6        Rajat     60
4          8        Rajat     95

In [85]:
g.min()

Student_id          6
Student_name    Rajat
Marks              60
dtype: object

In [86]:
g.max()

Student_id          8
Student_name    Rajat
Marks              95
dtype: object

In [87]:
g.count()

Student_id      2
Student_name    2
Marks           2
dtype: int64

In [88]:
group.describe()

Marks                                                 
             count  mean        std   min    25%   50%    75%   max
Student_name                                                       
Puneet         1.0  85.0        NaN  85.0  85.00  85.0  85.00  85.0
Rajat          2.0  77.5  24.748737  60.0  68.75  77.5  86.25  95.0
Sehaj          1.0  65.0        NaN  65.0  65.00  65.0  65.00  65.0
Shruti         1.0  70.0        NaN  70.0  70.00  70.0  70.00  70.0

# Concatenating

In [89]:
pd.concat([df1,df2])

Student_id Student_name  Marks
0          1       Kartik     60
1          2       Shruti     55
2          3        Aryan     70
3          4        Sehaj     80
4          5       Yamini     75
0          4       Shruti     70
1          5        Sehaj     65
2          6        Rajat     60
3          7       Puneet     85
4          8        Rajat     95

# Joining

In [90]:
left=pd.DataFrame({'A':['A0','A1','A2'],
                   'B':['B0','B1','B2']},
                   index=['K0','K1','k2'])
right=pd.DataFrame({'C':['C0','C2','C3'],
                   'D': ['D0','D2','D3']},
                    index=['k0','k2','k3'])
    


In [91]:
left

A   B
K0  A0  B0
K1  A1  B1
k2  A2  B2

In [92]:
right

C   D
k0  C0  D0
k2  C2  D2
k3  C3  D3

In [93]:
left.join(right)

A   B    C    D
K0  A0  B0  NaN  NaN
K1  A1  B1  NaN  NaN
k2  A2  B2   C2   D2

In [94]:
right.join(left)

C   D    A    B
k0  C0  D0  NaN  NaN
k2  C2  D2   A2   B2
k3  C3  D3  NaN  NaN

In [95]:
left.join(right,how='outer')

A    B    C    D
K0   A0   B0  NaN  NaN
K1   A1   B1  NaN  NaN
k0  NaN  NaN   C0   D0
k2   A2   B2   C2   D2
k3  NaN  NaN   C3   D3

In [96]:
left.join(right,how='inner')

A   B   C   D
k2  A2  B2  C2  D2

In [97]:
left.join(right,how='left')

A   B    C    D
K0  A0  B0  NaN  NaN
K1  A1  B1  NaN  NaN
k2  A2  B2   C2   D2

In [98]:
left.join(right,how='right')

A    B   C   D
k0  NaN  NaN  C0  D0
k2   A2   B2  C2  D2
k3  NaN  NaN  C3  D3

# Reshaping the Dataframe

In [99]:
df

Name     Subject  Marks  Avg Marks
0  Rohit      Python     70         43
1  Aryan         PHP     77         30
2  Ayush        Java     75         25
3   Yash         C++     67         40
4   Neha        Ruby     85         32
5  Suraj  Javascript     90         45

In [100]:
df.melt()

variable       value
0        Name       Rohit
1        Name       Aryan
2        Name       Ayush
3        Name        Yash
4        Name        Neha
5        Name       Suraj
6     Subject      Python
7     Subject         PHP
8     Subject        Java
9     Subject         C++
10    Subject        Ruby
11    Subject  Javascript
12      Marks          70
13      Marks          77
14      Marks          75
15      Marks          67
16      Marks          85
17      Marks          90
18  Avg Marks          43
19  Avg Marks          30
20  Avg Marks          25
21  Avg Marks          40
22  Avg Marks          32
23  Avg Marks          45

# More Index detail

In [102]:
a=pd.DataFrame(np.random.randn(4,4),index='A B C D '.split(),columns='W X Y Z'.split())
a

W         X         Y         Z
A -0.690130  0.971549 -1.149461  0.070504
B  0.919181 -0.171322 -0.027126 -0.336615
C  0.273488 -0.592768 -0.768131  2.365283
D -0.502478  0.749109 -0.196200 -1.554637

In [103]:
a.reset_index()

index         W         X         Y         Z
0     A -0.690130  0.971549 -1.149461  0.070504
1     B  0.919181 -0.171322 -0.027126 -0.336615
2     C  0.273488 -0.592768 -0.768131  2.365283
3     D -0.502478  0.749109 -0.196200 -1.554637

In [104]:
newindex='P Q R S'.split()

In [105]:
a['states']=newindex
a

W         X         Y         Z states
A -0.690130  0.971549 -1.149461  0.070504      P
B  0.919181 -0.171322 -0.027126 -0.336615      Q
C  0.273488 -0.592768 -0.768131  2.365283      R
D -0.502478  0.749109 -0.196200 -1.554637      S

In [106]:
a.set_index('states',inplace=True)


In [107]:
a

W         X         Y         Z
states                                        
P      -0.690130  0.971549 -1.149461  0.070504
Q       0.919181 -0.171322 -0.027126 -0.336615
R       0.273488 -0.592768 -0.768131  2.365283
S      -0.502478  0.749109 -0.196200 -1.554637

# Multi-Index and Index Hierarchy

In [108]:
#Index levels
outside=['A1','A1','A1','A2','A2','A2']
inside=[1,2,3,1,2,3]
index=list(zip(outside,inside))
index=pd.MultiIndex.from_tuples(index)

In [109]:
index

MultiIndex([('A1', 1),
            ('A1', 2),
            ('A1', 3),
            ('A2', 1),
            ('A2', 2),
            ('A2', 3)],
           )

In [110]:
f=pd.DataFrame(np.random.randn(6,2),index=index,columns=['B','C'])

Calling index hierarchy

In [111]:
f.loc['A2']

B         C
1 -2.392794 -0.406390
2  0.245246 -0.625290
3  0.765745 -0.104512

In [112]:
f.loc['A1'].loc[3]

B    0.751243
C    1.278450
Name: 3, dtype: float64

In [113]:
f.index.names

FrozenList([None, None])

In [114]:
f.index.names=['Group','Num']

In [115]:
f

B         C
Group Num                    
A1    1    0.311118 -0.124853
      2   -0.173276  1.703160
      3    0.751243  1.278450
A2    1   -2.392794 -0.406390
      2    0.245246 -0.625290
      3    0.765745 -0.104512

In [116]:
#to extract the subset of the data frame
f.xs('A1')

B         C
Num                    
1    0.311118 -0.124853
2   -0.173276  1.703160
3    0.751243  1.278450

In [117]:
f.xs(['A1',1])

C:\Users\bbnei\AppData\Local\Temp\ipykernel_7568\3179612059.py:1: FutureWarning: Passing lists as key for xs is deprecated and will be removed in a future version. Pass key as a tuple instead.
  f.xs(['A1',1])


B    0.311118
C   -0.124853
Name: (A1, 1), dtype: float64

In [118]:
f.xs(1,level='Num')

B         C
Group                    
A1     0.311118 -0.124853
A2    -2.392794 -0.406390

In [119]:
import numpy as np
a=np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [120]:
b=np.ones(10)

In [121]:
b

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [122]:
d=np.arange(10,51)
d

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [123]:
a=np.arange(0,9)
a.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [124]:
c=np.arange(10,51)
d=np.mod(c,2)==0
e=np.extract(d,c)
e

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [125]:
n=np.ones(9)
o=np.zeros(9)
n.reshape(3,3)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [126]:
o

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [127]:
np.random.randn(1)


array([-0.79768813])

In [128]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [129]:
x=np.eye(3)
x

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [130]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [131]:
mat[2:5,1:5]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [132]:
mat[3][4]

20

In [137]:
mat[3,4]

20

In [138]:
mat[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [139]:
mat[:5][4]

array([21, 22, 23, 24, 25])

In [140]:
mat[3:5]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [141]:
np.sum(mat,axis=0)

array([55, 60, 65, 70, 75])

In [142]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [143]:
a=np.arange(12,24).reshape(3,4)
a

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [144]:
np.random.randn(25)

array([ 2.0592926 ,  0.64852416, -0.1405969 ,  1.19966978, -0.5175074 ,
        0.90134005, -1.23047488,  0.34102662,  1.80414902,  0.49418801,
       -1.27083657,  0.97849557,  0.00670082, -1.73194559,  0.65076142,
        0.51825423,  0.82281773, -1.89334329, -0.12436587, -1.06437848,
       -0.82005546, -1.03805056,  0.20713156,  1.21847953, -0.82897225])

In [145]:
o[0:10]=5
o

array([5., 5., 5., 5., 5., 5., 5., 5., 5.])