Numpy

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


DEPRECATION: pandas 0.24.2 has a non-standard dependency specifier pytz>=2011k. pip 24.1 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of pandas or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063


In [2]:
import numpy as np

In [3]:
#Creating Numpy array
t=[1,2,3]
t


[1, 2, 3]

In [4]:
np.array(t)

array([1, 2, 3])

In [5]:
matrix=[[1,2,3],[4,5,6],[7,8,9]]
matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
np.array(matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
#Bulit in method
#arange
print(np.arange(0,10))
print(np.arange(0,11,2))

[0 1 2 3 4 5 6 7 8 9]
[ 0  2  4  6  8 10]


In [8]:
#Zeros and Ones
print(np.zeros(3))
print(np.zeros((3,5)))

[0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [9]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [10]:
#create an array filled with all ones upto 10 element
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [11]:
#linspace
np.linspace(0,10)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [12]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [13]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [14]:
np.linspace(0,20,7)

array([ 0.        ,  3.33333333,  6.66666667, 10.        , 13.33333333,
       16.66666667, 20.        ])

In [15]:
#Eye-creat an identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [16]:
#Random
np.random.rand(2)

array([0.63156263, 0.70972531])

In [17]:
np.random.rand(5,5)

array([[0.12670041, 0.12520082, 0.31973492, 0.43635422, 0.17284033],
       [0.52679373, 0.92751087, 0.65069535, 0.84442199, 0.3124049 ],
       [0.54214899, 0.51480365, 0.47632564, 0.17620141, 0.16178306],
       [0.69628379, 0.24503491, 0.92423808, 0.82812478, 0.76070673],
       [0.94840542, 0.79457773, 0.32572578, 0.51145905, 0.92173736]])

In [18]:
#randn
np.random.randn(5,5)

array([[-0.71100671,  0.6079391 , -0.41895292, -0.11454968,  0.19038356],
       [-0.18150281,  0.70783073,  0.05915926, -1.09544846, -0.99093294],
       [-1.92656426,  0.72797558, -0.31559152,  2.11740294, -0.37085808],
       [-0.07777231,  0.34306679,  1.57059703, -0.56371179, -0.28940666],
       [ 0.86710422,  0.22969875,  0.39446076, -1.41778098,  0.38595813]])

In [19]:
#randont
np.random.randint(1,100)

68

In [20]:
np.random.randint(1,100,10)

array([81, 69, 42, 49, 34, 53, 93, 84, 62, 18])

In [21]:
#guassion distribution
np.random.normal(1,100,10)

array([224.90514993, 198.72475734,  41.12914106, -43.45464364,
         7.94842131,  33.57460735,  87.08591045, -42.38048804,
       -30.89501057, 229.64785953])

In [22]:
#Array attribut and method
arr=np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [23]:
rod=np.arange(1,99)
rod

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [24]:
ran=np.random.randint(0,50,10)
ran

array([40, 35, 15, 13, 20,  3, 46, 16, 34, 23])

In [25]:
ran.max()

46

In [26]:
ran.argmax()

6

In [27]:
ran.min()

3

In [28]:
ran.argmin()

5

In [29]:
#Shape and Reshape
#vector
b=[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24]
c=np.array(b)
c.shape

(25,)

In [30]:
a=c.reshape(1,25)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [31]:
a.shape

(1, 25)

In [32]:
a.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [33]:
arr.reshape(25,1).shape

(25, 1)

In [34]:
a=[1,2,3,4,5,6,7,8,9]
c=np.array(a)
c.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
c.dtype

dtype('int32')

In [36]:
#create an empty array of(3,4) and full arrays of 3,3 with value 55
a=(np.empty((3,4),dtype=int))
a

array([[-1431655765,  1074440874, -1431655765,  1075489450],
       [          0,  1076101120, -1431655765,  1076538026],
       [-1431655765,  1076931242,           0,  1077149696]])

In [37]:
b=(np.full((3,3),55))
b

array([[55, 55, 55],
       [55, 55, 55],
       [55, 55, 55]])

In [38]:
#bincount
x=np.array([2,2,3,3,3,2,2,1,5,6,1])
y=np.bincount(x)
y

array([0, 2, 4, 3, 0, 1, 1], dtype=int32)

In [39]:
#max
y=np.bincount(x).max()
y

4

In [40]:
y=np.bincount(x).argmax()
y

2

In [41]:
#Find the max value
x=[4,18,2,8,3,15,14,15,20,20,12,6,3,15,12,13,19,14,81,23,44]

np.max(x)

81

# ndmin and dtype

In [42]:
a=np.array([1,2,3,4,5], ndmin=3)
print(a)

[[[1 2 3 4 5]]]


In [43]:
a=np.array([1,2,3,4,5], dtype=complex)
print (a)

[1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j]


# numpy.itemsize

In [44]:
x=np.array([1,2,3,4,5],dtype=np.int8)
x.itemsize

1

In [45]:
x=np.array([1,2,3,4,5],dtype=np.float32)
x.itemsize

4

# numpy.logspace

In [46]:
a=np.logspace(1,10,5)
print(a)

[1.00000000e+01 1.77827941e+03 3.16227766e+05 5.62341325e+07
 1.00000000e+10]


In [47]:
#set base of logspace to 2
a=np.logspace(1,10,10,base=2)
a

array([   2.,    4.,    8.,   16.,   32.,   64.,  128.,  256.,  512.,
       1024.])

# numpy indexing and selection

In [48]:
#creating a sample array
a=np.arange(0,10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
a[8]

8

In [50]:
a[1:5]

array([1, 2, 3, 4])

In [51]:
a[2::2]

array([2, 4, 6, 8])

In [52]:
a[6:9]

array([6, 7, 8])

# Broadcasting

In [53]:
a[0:5]=100
a

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9])

In [54]:
a=np.arange(0,11)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# Slice

In [55]:
slice_a=a[0:6]
slice_a

array([0, 1, 2, 3, 4, 5])

In [56]:
#change Slice
slice_a[:]=99
slice_a

array([99, 99, 99, 99, 99, 99])

In [57]:
a=np.array([[0.0,0.0,0.0],[10.0,10.0,10.0],[20.0,20.0,20.0],[30.0,30.0,30.0]])
b=np.array([1.0,2.0,3.0])
print(a)
print(b)
print('First Array + Second Array')
print(a+b)

[[ 0.  0.  0.]
 [10. 10. 10.]
 [20. 20. 20.]
 [30. 30. 30.]]
[1. 2. 3.]
First Array + Second Array
[[ 1.  2.  3.]
 [11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]


In [58]:
#indexing in 2D Array
b=np.array(([5,10,15],[20,25,30],[35,40,45]))
b

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [59]:
b[1,0]

20

In [60]:
b[0]

array([ 5, 10, 15])

In [61]:
b[0][2]

15

In [62]:
#2D arry slicing
b[:2,1:]

array([[10, 15],
       [25, 30]])

In [63]:
#bottom left column
b[1:,:2]

array([[20, 25],
       [35, 40]])

In [64]:
b[2,2]

45

In [65]:
b[2,:]

array([35, 40, 45])

In [66]:
#use of ellipse
b[...,1]

array([10, 25, 40])

In [67]:
#using advanced index for column
c=b[1:4,[1,2]]
c

array([[25, 30],
       [40, 45]])

In [68]:
#Fancy indexing
d=np.zeros((10,10))
d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [69]:
#Length of array
d_length=d.shape[0]
d_length

10

In [70]:
d.shape

(10, 10)

In [71]:
#Set up array
for i in range(d.shape[0]):
    d[i]=i
d


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [72]:
#Fancy indexing uses 2 square bracket
d[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [73]:
#Allows in any order
d[[6,4,2,7]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

In [74]:
#Selection or boolean Array indexing
a=np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [75]:
a>4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [76]:
bool_a=a>4
bool_a

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [77]:
#We have to use it as a indexing value
print(a[bool_a])
print(a[a>4])

[ 5  6  7  8  9 10]
[ 5  6  7  8  9 10]


In [78]:
#nan=not a number
a=np.array([np.nan,1,2,np.nan,3,4,5])
a[~np.isnan(a)]

array([1., 2., 3., 4., 5.])

In [79]:
a=np.array([1,2+6j,5,3.5+5j])
a[np.iscomplex(a)]

array([2. +6.j, 3.5+5.j])

In [80]:
b=[8,14,15,16,17,18,19,20,21,22,23,24,25]
c=np.array(b)
c[c>18]

array([19, 20, 21, 22, 23, 24, 25])

In [81]:
#Numpy operation
#Arithmetic
import numpy as np
a=np.arange(0,10)

In [82]:
a*a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [83]:
a+a

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [84]:
a-a

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [85]:
a/a

C:\ProgramData\Anaconda32\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [86]:
a**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [87]:
#universal array function 
np.sqrt(a)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [88]:
#calculating exponential
np.exp(a)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [89]:
np.max(a)

9

In [90]:
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [91]:
np.log(a)

C:\ProgramData\Anaconda32\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [92]:
#addition
a=np.array([10,42,18,80])
b=np.array([8,30,10,50])
c=np.add(a,b)
c

array([ 18,  72,  28, 130])

In [93]:
#Subtraction
d=np.subtract(a,b)
d

array([ 2, 12,  8, 30])

In [94]:
#Multiply
e=np.multiply(a,b)
e

array([  80, 1260,  180, 4000])

In [95]:
#division
f=np.divide(a,b)
f

array([1.25, 1.4 , 1.8 , 1.6 ])

In [96]:
#sum of each column in the matrix and for rows is 1
s=10
c=np.sum(s,axis=0)
c


10

In [97]:
b=np.arange(0,10)

In [98]:
c=[1,2,3,14,15,16,17,18,19]
g=np.array(c)
g

array([ 1,  2,  3, 14, 15, 16, 17, 18, 19])

In [99]:
g=np.array([1,2,3,14,15,16,17,18,19])
g

array([ 1,  2,  3, 14, 15, 16, 17, 18, 19])

In [100]:
print(np.char.upper("hello"))

HELLO


In [101]:
print(np.char.center('hello',20,fillchar='*'))

*******hello********


In [102]:
print(np.char.multiply(' Hello ', 3))

 Hello  Hello  Hello 


In [103]:
print(np.char.add(['hello','hi'],['Suraj','Puneet']))

['helloSuraj' 'hiPuneet']


In [104]:
#Mathematical Function
a=np.array([0,30,45,60])
print('Sine values for angles: ')
print(np.sin(a*np.pi/100))
print('/n')
print('Cosine values for angles')
print(np.cos(a*np.pi/100))
print('/n')
print('Tangent values for given angles: ')
print(np.tan(a*np.pi/100))
print('/n')

Sine values for angles: 
[0.         0.80901699 0.98768834 0.95105652]
/n
Cosine values for angles
[ 1.          0.58778525  0.15643447 -0.30901699]
/n
Tangent values for given angles: 
[ 0.          1.37638192  6.31375151 -3.07768354]
/n


In [105]:
#Function for Rounding
a=np.array([1.0,5.55,123,0.567,25.532])
np.around(a, decimals=1)

array([  1. ,   5.6, 123. ,   0.6,  25.5])

In [106]:
a=np.array([-1.7,1.5,-0.2,0.6,10])
np.floor(a)

array([-2.,  1., -1.,  0., 10.])

In [107]:
np.ceil(a)

array([-1.,  2., -0.,  1., 10.])

In [108]:
#Statistical Function
a

array([-1.7,  1.5, -0.2,  0.6, 10. ])

In [109]:
np.reciprocal(a)

array([-0.58823529,  0.66666667, -5.        ,  1.66666667,  0.1       ])

In [110]:
a=np.array([10,100,1000])
b=np.array([1,2,3])
np.power(a,b)

array([        10,      10000, 1000000000], dtype=int32)

In [111]:
np.percentile(a,50)

100.0

In [112]:
a=np.array([[80,95,10],[20,30,40]])
np.median(a)

35.0

In [113]:
np.median(a,axis=0)#Column

array([50. , 62.5, 25. ])

In [114]:
np.median(a,axis=1)#Rows

array([80., 30.])

In [115]:
np.mean(a)

45.833333333333336

In [116]:
#Numpy.amin() and numpy.amax()
a=np.array([[3,7,5],[8,4,3],[2,4,9]])
a

array([[3, 7, 5],
       [8, 4, 3],
       [2, 4, 9]])

In [117]:
np.amin(a,1)#minimum 

array([3, 3, 2])

In [118]:
np.amin(a,0)#minimum 

array([2, 4, 3])

In [119]:
np.amax(a,1)#maximum

array([7, 8, 9])

In [120]:
np.amax(a,0)

array([8, 7, 9])

In [121]:
a

array([[3, 7, 5],
       [8, 4, 3],
       [2, 4, 9]])

In [122]:
#numpy.ptp
np.ptp(a, axis=1)


array([4, 5, 7])

In [123]:
np.ptp(a, axis=0)

array([6, 3, 6])

In [124]:
#numpy.std
np.std(a)

2.309401076758503

In [125]:
#numpy.var (variance)
np.var(a)

5.333333333333333

In [126]:
a

array([[3, 7, 5],
       [8, 4, 3],
       [2, 4, 9]])

In [127]:
#Sort
np.sort(a)

array([[3, 5, 7],
       [3, 4, 8],
       [2, 4, 9]])

In [128]:
#numpy.argsort()
np.argsort(a)

array([[0, 2, 1],
       [2, 1, 0],
       [0, 1, 2]], dtype=int32)

In [129]:
#numpy.argmax and numpy.argmin()
np.argmax(a)

8

In [130]:
a.flatten()

array([3, 7, 5, 8, 4, 3, 2, 4, 9])

In [131]:
np.argmin(a)

6

In [132]:
#numpy.nonzero()
g=np.array([[30,40,0],[0,20,10],[50,0,60]])
g

array([[30, 40,  0],
       [ 0, 20, 10],
       [50,  0, 60]])

In [133]:
np.nonzero(g)

(array([0, 0, 1, 1, 2, 2], dtype=int32),
 array([0, 1, 1, 2, 0, 2], dtype=int32))

In [134]:
g

array([[30, 40,  0],
       [ 0, 20, 10],
       [50,  0, 60]])

In [135]:
#numpy.where()
g[np.where(g>30)]

array([40, 50, 60])

In [136]:
#create a matrix of 20 to 60 and its matrix is(5,5)
a=np.arange(20,60)
c=a.reshape(5,8)
c

array([[20, 21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43],
       [44, 45, 46, 47, 48, 49, 50, 51],
       [52, 53, 54, 55, 56, 57, 58, 59]])

In [137]:
# numpy.extract()
x=np.arange(9.).reshape(3,3)
x

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [138]:
condition=np.mod(x,2)==0
condition

array([[ True, False,  True],
       [False,  True, False],
       [ True, False,  True]])

In [139]:
np.extract(condition,x)

array([0., 2., 4., 6., 8.])

Linear Algebra 
np.dot()
-return the dot product of two array

In [140]:
a=np.array([[1,2],[3,4]])
b=np.array([[11,12],[13,14]])
np.dot(a,b)

array([[37, 40],
       [85, 92]])

In [141]:
#return the dot product of the two matrices
np.vdot(a,b)

130

In [142]:
#matrix multiplication
np.matmul(a,b)


array([[37, 40],
       [85, 92]])

In [143]:
#find determinant
np.linalg.det(a)

-2.0000000000000004

In [144]:
#find inverse
np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])